<div>
    <div class="heading">
        <h1 class="text-5xl py-4">Yireo Loki Checkout</h1>
        <h2 class="text-3xl py-4">A low-key Magewire-based developer-focused checkout for Magento 2</h2>
        <p>With Magewire, you can build rapidly UI components. However, building a checkout is a burden. That's where we
            do the heavy lifting. With our Loki Checkout, you get your hands on a developer-friendly Magewire-driven
            checkout, that is easy to extend. And it is beautiful out-of-the-box too!
        </p>
    </div>

    <div class="prose">
        <h3>Technology stack</h3>
        <ul>
            <li>Supporting both Luma Theme and Hyvä Theme</li>
            <li>Built on top of Magewire 1, Alpine 3 and Tailwind 3</li>
            <li>Requires Magento 2.4.7 or newer. Requires PHP 8.3 or newer</li>
            <li>Playwright tests & Integration Tests covering most if not all features</li>
        </ul>

        <h3>Benefits</h3>
        <ul>
            <li>Granular components and templates for everything, to keep down legacy</li>
            <li>If you know XML layout, Magewire, Blocks and ViewModels, you will know Loki</li>
            <li>Theming error messages, adding PHP or JS validation rules - it is all made easy</li>
            <li>And all forms are ready for accessibility</li>
        </ul>

        <h3>Integrations</h3>
        <ul>
            <li>Mollie, Buckaroo, MultiSafepay and more to follow</li>
            <li>Post NL, Postcode NL, DHL, Geissweb</li>
        </ul>
        <small class="text-sm">
            More integrations will follow, but the above is the current focus.
        </small>

        <h3>Pricing</h3>
        <p>It will be competitive but fair</p>

        <h3>Release plan</h3>
        <ul>
            <li>Today the core works and support for Dutch payment providers is underway</li>
            <li>In November 2024, we will be running the first 2 projects</li>
            <li>In December 2024, private betas follow</li>
            <li>In Q1 2025, we are opening up for a wider public</li>
        </ul>
        <p>However, we are not aiming to take over the market. You will need to work with us to make this work.</p>
    </div>

    <div class="cta">
        <h1 class="text-5xl py-4">Sometimes a bit of mischief can be healthy</h1>
        <h2 class="text-3xl py-4">Soon more news</h2>
    </div>

</div>

<style>
    .heading {
        position: relative;
        background-image: url(https://www.yireo.com/images/headers/loki-checkout.jpg);
        background-size: cover;
        padding: 100px;
        margin-bottom: 50px;
        text-align: center;
        box-shadow: inset 0 0 0 1000px rgba(0, 0, 0, .5);
        color: white;
    }

    .prose {
        padding: 40px;
    }

    .cta {
        background: rgb(131,236,121);
        background: linear-gradient(90deg, rgba(131,236,121,1) 0%, rgba(161,161,161,1) 0%, rgba(114,118,166,1) 37%, rgba(199,199,199,1) 100%);
        color: white;
        padding: 100px;
        margin-bottom: 50px;
        text-align: center;
    }

    .cta > .button {
        display: inline-flex;
        border-width: 2px;
        border-color: orange;
        color: #222;
        padding-left: 1.5rem;
        padding-right: 1.5rem;
    }
</style>
